# Pyscho Parent

Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming Easter egg hunt is to use NumPy . You represent the field as a 10x10 array of 0s.

In [1]:
import numpy as np

field = np.zeros(shape = (10, 10))

print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
#Solution
np.set_printoptions(linewidth=999)
generator = np.random.default_rng(seed=1234)
nums = np.round(generator.normal(loc=0.0,scale=1.0,size=20),2)
locs = generator.choice(field.size,20,replace=False)
field.ravel()[locs]=nums
field

array([[ 0.52,  0.  ,  0.  , -1.48,  0.  ,  2.91,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , -1.27,  0.  ,  0.  ,  0.  , -1.6 ,  0.  ,  1.73,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.43,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.34,  0.  ,  0.  ,  0.  , -1.67],
       [ 0.  ,  0.86,  0.74,  0.  ,  0.  ,  0.  ,  1.32,  0.  ,  0.52,  0.  ],
       [ 0.  , -1.  ,  0.  ,  0.  ,  0.  ,  0.15,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , -0.51,  0.  , -0.86,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -2.16,  0.  ,  0.95,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.06]])